/*
 * To change this license header, choose License Headers in Project Properties.
 * Toj change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Metodos.LRU;
import java.util.List;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Interfaz_LRU extends javax.swing.JFrame {

    String cantidadpaginas[];
    int ubicacion;
    DefaultListModel lista;
    List<String> valores = new ArrayList<String>();
    

    /**
     * Creates new form Interfaz_LRU
     */
    public Interfaz_LRU() {
        initComponents();
        jButtonAAlgortimo.setEnabled(false);
        jButtonEditar.setEnabled(false);

        jTextFieldNReemplazo.setEditable(false);
        lista = new DefaultListModel();
        this.setIconImage(new ImageIcon(getClass().getResource("/Imagenes/1.jpg")).getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNPaginas = new javax.swing.JTextField();
        jTextFieldMPagina = new javax.swing.JTextField();
        jButtonAgregar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListNpaginas = new javax.swing.JList<>();
        jTextFieldNReemplazo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableAlgoritmo = new javax.swing.JTable();
        jButtonAAlgortimo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelNFallos = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Algoritmo LRU");

        jLabel2.setText("Numero Paginas:");

        jLabel3.setText("Marco de Paginas:");

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jListNpaginas.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jListNpaginas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListNpaginasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListNpaginas);

        jLabel5.setText("Numero Reemplazar:");

        jTableAlgoritmo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableAlgoritmo);

        jButtonAAlgortimo.setText("Aplicar Algoritmo");
        jButtonAAlgortimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAAlgortimoActionPerformed(evt);
            }
        });

        jLabel4.setText("Numero Fallos:");

        jLabelNFallos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldMPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 297, Short.MAX_VALUE)
                        .addComponent(jButtonAgregar)
                        .addGap(221, 221, 221)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(33, 33, 33)
                .addComponent(jTextFieldNReemplazo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabelNFallos, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jButtonAAlgortimo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldNPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addComponent(jButtonAgregar)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldMPagina, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldNReemplazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonAAlgortimo))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelNFallos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSalir)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAAlgortimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAAlgortimoActionPerformed
        // TODO add your handling code here:
       mostrarMatriz();

    }//GEN-LAST:event_jButtonAAlgortimoActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNPaginas.getText().equals("") || jTextFieldMPagina.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Ingrese datos porfavor");
        } else {

            int cp = Integer.parseInt(jTextFieldNPaginas.getText());
            cantidadpaginas = new String[cp];
            for (int c = 0; c < cp; c++) {
                cantidadpaginas[c] = (JOptionPane.showInputDialog(null, "Ingrese valor de paginas [" + (c + 1) + "]"));
                valores.add(cantidadpaginas[c]);
                lista.addElement(String.valueOf(valores.get(c)));

            }
            jListNpaginas.setModel(lista);
            jButtonAAlgortimo.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        // TODO add your handling code here:
        if (jTextFieldNReemplazo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe llenar el recuadro");
        } else {
            lista.set(ubicacion, jTextFieldNReemplazo.getText());
            jListNpaginas.setModel(lista);
            cantidadpaginas[ubicacion] = jTextFieldNReemplazo.getText();
            
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jListNpaginasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListNpaginasMouseClicked
        // TODO add your handling code here:
        ubicacion = jListNpaginas.getSelectedIndex();
        System.out.println(ubicacion);

        jTextFieldNReemplazo.setEditable(true);
        jButtonEditar.setEnabled(true);
    }//GEN-LAST:event_jListNpaginasMouseClicked

    public void mostrarMatriz() {
        LRU lru = new LRU();
        lru.setCantidadMarco(Integer.parseInt(jTextFieldMPagina.getText()));
        lru.setCantidadPaginas(Integer.parseInt(jTextFieldNPaginas.getText()));
        lru.setPaginas(cantidadpaginas);
        lru.lru();
        int cantidadMarco = Integer.parseInt(jTextFieldMPagina.getText());
        int cantidadPaginas = Integer.parseInt(jTextFieldNPaginas.getText());
        String matriz[][] = lru.RetornarMatriz();
        jTableAlgoritmo.removeAll();
        Object vector[] = new Object[cantidadPaginas];

        for (int i = 0; i < cantidadPaginas; i++) {
            vector[i] = "Pag" + (i + 1);
        }
        DefaultTableModel modelo = new DefaultTableModel(null, vector);
        String arreglo[] = new String[cantidadPaginas];
        for (int i = 0; i < cantidadMarco; i++) {
            for (int j = 0; j < cantidadPaginas; j++) {
                  
               if (matriz[i][j].equals("-")) {
                 arreglo[j] = " ";
              } else {
                 arreglo[j] = matriz[i][j];
              }
            }
            modelo.addRow(arreglo);
            jTableAlgoritmo.setModel(modelo);
        }
        int fallos[] = lru.RetornarVector();
        for (int i = 0; i < fallos.length; i++) {
            arreglo[i] = String.valueOf(fallos[i]);
        }
        modelo.addRow(arreglo);
        jTableAlgoritmo.setModel(modelo);
        jLabelNFallos.setText(String.valueOf(lru.contFallos()));
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_LRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_LRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_LRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_LRU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_LRU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAAlgortimo;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelNFallos;
    private javax.swing.JList<String> jListNpaginas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableAlgoritmo;
    private javax.swing.JTextField jTextFieldMPagina;
    private javax.swing.JTextField jTextFieldNPaginas;
    private javax.swing.JTextField jTextFieldNReemplazo;
    // End of variables declaration//GEN-END:variables
}
